### ISSUE TITLE
Ukol 07

### ISSUE THREAD

**Issue by LenkaDostalova** [LenkaDostalova/Python-jaro-22#7]
https://github.com/LenkaDostalova/Python-jaro-22/blob/main/ukol-07_Posta.py

Ahoj Aneto,

v regex101 mi fungoval regulární výraz:
\d{3} \d{2} (\w* *)*
ale v pythonu ne, pouze bez kulatých závorek:
\d{3} \d{2} \w* *\w* *\w* *
tak jsem nakonec skončila u výrazu:
\d{3} \d{2} [\w ]*
který je elegantnější.

Ale zajímalo by mě, k čemu tedy v pythonu kulaté závorky slouží, nebo jak jinak označit skupinu znaků. Četla jsem si nápovědu a nejsem z toho moudrá.

Díky,
Lenka

**Comment by AnetaPopelova** [comment]
Ahoj, je to moc hezke reseni. 

Zavorky slouzi k vyberu znaku v nich: pomoci regexu najdes najeky vzorec (pattern) a pomoci uvozovek si z nej vyzobes jen tu cast, kterou chces. 

Priklad: potrebujes najit vsechna PSC, ale vytahnout z nich jen prvni tri znaky. Kdybys hledala jen \d{3}, muze to najit veci, co nejsou PSC. Proto zavorky.

**Comment by AnetaPopelova** [comment]
K druhe casti otazky: trochu jsem si s tim hrala... zalezi i na dalsich faktorech (muzes pouzit findall, search, match... https://www.guru99.com/python-regular-expressions-complete-tutorial.html) a podle toho se to chovani zjevne lisi.

Tohle je vzorove reseni (od Lidy) k telefonnim cislum, ktere nam fungovalo v regex101.
` ^(\+420 ?)?\d{3} ?\d{3} ?\d{3}$`

Nebude ale fungovat s `findall`:

```
import re

nazev_souboru = 'cisla.txt'
with open(nazev_souboru, encoding='utf-8') as vstup: 
    telefony = vstup.read() 

regex1 = re.compile(r"[\+420 ?]? ?\d{3} ?\d{3} ?\d{3}")
regex2 = re.compile(r"(\+420 ?)? ?\d{3} ?\d{3} ?\d{3}")

matching1 = regex1.findall(telefony)
print(matching1)

matching2 = regex2.findall(telefony)
print(matching2)

# Vysledek
['+420789788', '773 789 543', '788789778', '+420 789 788']
['+420', '', '', '+420 ']
```

No ale `match` to neresi.
```
import re

telefony = ['+420789788787', '773 789 543', '773 745 65A', '7887897781', '+420 789 788 787']

regex1 = re.compile(r"[\+420 ?]? ?\d{3} ?\d{3} ?\d{3}")
regex2 = re.compile(r"(\+420 ?)? ?\d{3} ?\d{3} ?\d{3}")

matching1 = list(filter(regex1.match, telefony))
print(matching1)

matching2 = list(filter(regex2.match, telefony))
print(matching2)

# Vysledek
['+420789788787', '773 789 543', '7887897781', '+420 789 788 787']
['+420789788787', '773 789 543', '7887897781', '+420 789 788 787']
```

**Comment by AnetaPopelova** [comment]
Dnes jsem se dozvedela, ze spravne reseni seskupovani v regexu je pomoci `?:`, vice tady:

https://stackoverflow.com/questions/3705842/what-does-do-in-regex
